[package]
name = "project-theseus"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
gibson = { package = "libgibson", git = "https://github.com/femboy2112/libgibson", tag = "v0.4.0", features = ["audio-cpal"] }
rand = "0.8"

[dev-dependencies]
portable-pty = "0.9"
