#!/usr/bin/env python3
"""Bounded Linux PTY witness. Drains continuously and always reaps direct child.

ANSI is observed only, never generated by the lab presentation. Input escape
is an actual keyboard action. No persisted raw transcript; emit small receipts.
"""
import errno
import fcntl
import json
import os
import pty
import select
import struct
import subprocess
import sys
import termios
import time


def capture(binary, width, height, color):
    master, slave = pty.openpty()
    fcntl.ioctl(master, termios.TIOCSWINSZ, struct.pack("HHHH", height, width, 0, 0))
    initial = termios.tcgetattr(slave)
    os.set_blocking(master, False)
    proc = subprocess.Popen([binary, "--at=10000", "--color=" + color, "--seconds=4"],
                            stdin=slave, stdout=slave, stderr=slave, start_new_session=True)
    data = bytearray()
    start = time.monotonic()
    actions = [(0.3, b" "), (0.5, b"\t"), (0.7, b"n"), (1.4, b"\x1b")]
    resized = False
    try:
        while time.monotonic() - start < 6:
            elapsed = time.monotonic() - start
            while actions and elapsed >= actions[0][0]:
                os.write(master, actions.pop(0)[1])
            if not resized and elapsed > 0.9:
                fcntl.ioctl(master, termios.TIOCSWINSZ, struct.pack("HHHH", 24, 56, 0, 0))
                resized = True
            if select.select([master], [], [], 0.02)[0]:
                try:
                    chunk = os.read(master, 65536)
                    data.extend(chunk)
                except OSError as exc:
                    if exc.errno != errno.EIO:
                        raise
            if len(data) > 8 * 1024 * 1024:
                raise AssertionError("output budget exceeded")
            if proc.poll() is not None:
                break
        assert proc.poll() == 0, "nonzero exit or timeout"
        restored = termios.tcgetattr(slave) == initial
        assert restored, "terminal attributes not restored"
        assert b"\x1b[?1049l" in data, "alternate screen not left"
        assert b"panic" not in data, "panic in capture"
        return dict(binary=os.path.basename(binary), size=[width, height], color=color,
                    exit=proc.returncode, bytes=len(data), termios_restored=restored,
                    resized=resized, seconds=round(time.monotonic()-start, 3))
    finally:
        if proc.poll() is None:
            proc.kill()
        proc.wait(timeout=2)
        os.close(master)
        os.close(slave)


if __name__ == "__main__":
    for binary in sys.argv[1:]:
        for w,h,color in [(56,24,"mono"),(120,32,"truecolor"),(160,40,"ansi16")]:
            print(json.dumps(capture(binary,w,h,color)), flush=True)
